services:

  auth-api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    image: sample-auth-service
    ports:
      - "5001:8080"
    env_file:
      - .env
    depends_on:
      - auth-db
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/8080'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  auth-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Dev@123456
    ports:
      - "1434:1433"
    volumes:
      - auth_sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433'"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 120s

volumes:
  auth_sql_data:
