name: SampleAuthService Master Pipeline

on:
  push:
    branches:
      - master
    paths:
      - 'SampleAuthService/**'

jobs:
  full-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Start Auth Infrastructure
        run: docker compose -f SampleAuthService/deployment/docker-compose.yml up -d auth-db rabbitmq-auth redis-auth

      - name: Wait for MSSQL
        run: sleep 90

      - name: Restore
        run: dotnet restore SampleAuthService/src/SampleAuthService.Api/SampleAuthService.Api.csproj

      - name: Build
        run: dotnet build SampleAuthService/src/SampleAuthService.Api/SampleAuthService.Api.csproj --no-restore

      - name: Unit Tests
        run: dotnet test SampleAuthService/tests/SampleAuthService.UnitTests/SampleAuthService.UnitTests.csproj --no-build

      - name: Integration Tests
        run: dotnet test SampleAuthService/tests/SampleAuthService.IntegrationTests/SampleAuthService.IntegrationTests.csproj --no-build

      - name: Publish API
        run: dotnet publish SampleAuthService/src/SampleAuthService.Api/SampleAuthService.Api.csproj -c Release -o out

      - name: Docker Build
        run: docker build -t sample-auth-service -f SampleAuthService/deployment/Dockerfile .