name: SampleAuthService PR Checks

on:
  push:
    branches-ignore:
      - master
    paths:
      - 'SampleAuthService/**'
  pull_request:
    paths:
      - 'SampleAuthService/**'

jobs:
  build-unit:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: SampleAuthService

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore
      - run: dotnet build --no-restore

      - run: dotnet test tests/SampleAuthService.UnitTests --no-build