name: ServiceName PR Validation

on:
  pull_request:
    branches: [master]
    paths:
      - 'ServiceName/**'

jobs:
  build-unit:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ServiceName

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore
      - run: dotnet build --no-restore

      - name: Unit Tests
        run: dotnet test tests/ServiceName.UnitTests --no-build